import React from "react";
import { ShieldCheck, Scale } from "lucide-react";

export function PrivacyView() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-12 font-sans leading-relaxed text-slate-600 dark:text-slate-300">
      <h1 className="text-3xl font-extrabold text-slate-900 dark:text-white flex items-center gap-2.5 mb-6">
        <ShieldCheck className="w-8 h-8 text-green-500" />
        Privacy Policy
      </h1>
      <p className="text-xs text-slate-400 mb-6">Last Updated: July 12, 2026</p>

      <div className="space-y-6 text-sm">
        <section className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-6 rounded-2xl">
          <h2 className="font-extrabold text-slate-900 dark:text-white text-md mb-3">1. Information We Do NOT Collect</h2>
          <p>
            Unlike typical career databases, Resume Roaster AI does not store, index, or distribute your resume documents permanently. Your uploaded PDF, DOCX, or text content is processed in-memory, parsed, passed to Google Gemini API for roasting feedback, and instantly discarded from our cloud servers.
          </p>
        </section>

        <section className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-6 rounded-2xl">
          <h2 className="font-extrabold text-slate-900 dark:text-white text-md mb-3">2. Browser Storage & Archive History</h2>
          <p>
            Your analysis and roast history is stored 100% locally on your browser's local storage (localStorage) under your email profile. We have no backend service to inspect, search, or access your saved records. Clearing your browser cache will permanently clear your local history.
          </p>
        </section>

        <section className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-6 rounded-2xl">
          <h2 className="font-extrabold text-slate-900 dark:text-white text-md mb-3">3. External Service Integrations</h2>
          <p>
            We use Google Gemini AI services to parse and analyze your text. We do not pass any secondary analytics, tracking, or personal identifier coordinates to Gemini. Your text is evaluated strictly for semantic spelling, density, and formatting rules.
          </p>
        </section>
      </div>
    </div>
  );
}

export function TermsView() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-12 font-sans leading-relaxed text-slate-600 dark:text-slate-300">
      <h1 className="text-3xl font-extrabold text-slate-900 dark:text-white flex items-center gap-2.5 mb-6">
        <Scale className="w-8 h-8 text-purple-600" />
        Terms of Service
      </h1>
      <p className="text-xs text-slate-400 mb-6">Last Updated: July 12, 2026</p>

      <div className="space-y-6 text-sm">
        <section className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-6 rounded-2xl">
          <h2 className="font-extrabold text-slate-900 dark:text-white text-md mb-3">1. Disclaimer of Professional Humiliation</h2>
          <p>
            Resume Roaster AI is an entertainment-first audit utility. The feedback, score metrics, and witty roast commentaries generated by our AI personalities are intended solely for humor and personal improvement. You agree not to sue or blame our system if you experience emotional damage after being told your experiences look like a middle-school science project.
          </p>
        </section>

        <section className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-6 rounded-2xl">
          <h2 className="font-extrabold text-slate-900 dark:text-white text-md mb-3">2. No Guarantee of Job Landing</h2>
          <p>
            Applying our suggested fixes, formatting rules, and keyword density advice will significantly enhance your ATS compatibility and recruiter readability. However, we do not guarantee employment, salary raises, or positive interview calls. The hiring process is ultimately complex and human.
          </p>
        </section>
      </div>
    </div>
  );
}
